// <auto-generated />
namespace _01CodeFirst.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setSubjecttorequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setSubjecttorequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151810086_set Subject to required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
