// <auto-generated />
namespace _01CodeFirst.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addconnectionTeachertoSubject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addconnectionTeachertoSubject));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151739208_add connection Teacher-to-Subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
