// <auto-generated />
namespace _01CodeFirst.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addSubjecttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSubjecttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151736289_add Subject table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
